/**
 * Witty one-liners and sarcastic comments for various code smells.
 * Each array is randomly sampled when that smell is detected.
 */
export const CODE_SMELL_QUIPS = {
  godClass: [
    'This class does everything — including things it definitely should not.',
    'It\'s not a god class, it\'s a *deity* class. Much worse.',
    'Swiss Army knife? More like a hardware store.',
    'This class has a God Complex and sees a therapist three times a week.',
    'The responsibility distribution: this class gets 90%, the rest split 10%.',
    'Violates Single Responsibility so hard the compiler winced.',
    'A class that does literally everything is technically a class that does nothing well.',
    'This is what happens when someone says "just add it here."',
    'If it\'s not broken, don\'t fix it. This is *very* broken.',
    'Refactoring this would be considered a crime against humanity.',
    'This class is what happens when you skip the design phase.',
    'The Swiss Army knife that thinks it\'s Excalibur.',
    'Single Responsibility Principle? Never heard of her.',
    'This is the class that cried "refactor me" for five years.',
    'The omniscient, omnipotent class. Missing the omnipresent part.',
    'Responsibilities? More like suggestions it chooses to ignore.',
    'This class attended every meeting and volunteered for everything.',
    'Separation of concerns? More like aggregation of everything.',
    'If this class gets any bigger, it\'ll have its own gravitational field.',
    'The class that said yes to every feature request.',
    'Doing everything except the one thing it was supposed to do.',
  ],
  chunkiClass: [
    'Not quite a god class, but it\'s clearly trying.',
    'Getting chunky. Real chunky. Kitchen sink chunky.',
    'This class collects responsibilities like I collect old hoodies.',
    'Warning: High risk of becoming a god class in the next sprint.',
    'Doing a lot of things. Not doing any of them elegantly.',
    'The class that tried to be everything and succeeded at nothing.',
    'Split me up before I gain sentience.',
    'Approaching critical mass. Recommend eject before touchdown.',
    'Stuffed like a Thanksgiving turkey.',
    'The definition of "getting out of hand."',
    'This is your sign to refactor. Seriously.',
    'One more responsibility and it gets its own Wikipedia page.',
    'Bigger than it has any right to be.',
    'Creeping featurism: the long, slow descent into bloat.',
    'Started as a utility, ended as a dumping ground.',
    'This class is the filing cabinet we all wish we hadn\'t opened.',
    'Too many cooks in this method kitchen.',
    'Bloat: it\'s not a feature, it\'s a lifestyle.',
    'The class that grew without permission.',
  ],
  theNovel: [
    'No one has read this fully since it was written, including its author.',
    'At what point does a class become a novella?',
    'This is the War and Peace of source files.',
    'So long it requires bookmarks to navigate.',
    'Pretty sure this violates some Geneva Convention.',
    'Your future self will curse your name.',
    'If compressed, this could be several actual files.',
    'A masterpiece of procrastination. Edit later. (You won\'t.)',
    'This file comes with a table of contents.',
    'Need to take a break halfway through reading? I do.',
    'Remember when files were measured in kilobytes? Good times.',
    'A tome. An epic. A code tragedy.',
    'Reading this requires industrial-strength coffee.',
    'The sequel nobody asked for is somewhere in here.',
    'This is what "legacy code" looks like.',
    'This file walks the line between code and autobiography.',
    'A file so long, it needs its own version control.',
    'Honestly, at this point, might as well publish it as a book.',
    'The developer\'s extended cut: now 500% longer.',
    'This isn\'t code, it\'s a commitment to verbosity.',
    'The Infinite Jest of Java.',
  ],
  theEssay: [
    'Technically a type, functionally a lifestyle choice.',
    'This class needs a thesis advisor.',
    'Long enough to deserve its own README.',
    'It\'s not dead code, it\'s *literature*.',
    'Why is this file so introspective?',
    'Novel-length commit messages incoming.',
    'If you squint, it\'s almost a short story.',
    'Substantial. Weighty. Unnecessarily verbose.',
    'This is what happens when "just one more method" repeats 50 times.',
    'Bloated with ambition and methods.',
    'The class that kept evolving without refactoring.',
    'Somewhere between a class and a thesis.',
    'This is what happens when you never hit save and refactor.',
    'The Goldilocks of bloat: not quite a novel, but definitely chunky.',
    'An essay on why you should split things up.',
  ],
  labyrinth: [
    'A maze Theseus would nope out of.',
    'So many paths, so little time to test them all.',
    'The Minotaur lives here. We don\'t go there.',
    'Flowchart? More like *flowjart*.',
    'Your debugger is now your therapist.',
    'This class has an Escher painting as its architecture.',
    'Cyclomatic complexity? More like cyclopean complexity.',
    'Even the test suite gets lost in here.',
    'The paths branch so much, birds nest in the code.',
    'A logic puzzle wrapped in conditional statements.',
    'If statements having if statements having if statements...',
    'This is what happens when someone fears the extract method refactoring.',
    'The butterfly effect: one input, infinite possible outputs.',
    'Code so convoluted, it needs its own GPS.',
    'The control flow graph that broke D3.js.',
    'More conditionals than a Choose Your Own Adventure book.',
    'Debugging this is archaeological work.',
    'The flowchart requires a flowchart.',
    'Navigation: abandon hope, all ye who enter here.',
    'This logic tree has become a logic forest.',
  ],
  branchCollector: [
    'Pick one execution path and pray the tests cover it.',
    'Branch prediction: mission impossible.',
    'Code branching so heavy, the tree is a forest.',
    'Testing this exhaustively would require 500 monkeys.',
    'Every if statement spawns two universes.',
    'The if-else chains here are older than some languages.',
    'More branches than a decision tree in a machine learning paper.',
    'Reaching branch coverage: not on this lifetime.',
    'The parallel universe generator.',
    'Schrödinger\'s execution path: is it covered? Yes and no.',
    'Your test suite has test suite.',
    'Coverage reports? More like coverage fiction.',
    'The exponential explosion simulator.',
    'Test case: exists? Yes. Coverage: lol.',
    'Your CI/CD pipeline\'s worst enemy.',
    'Branch out or branch out. No middle ground.',
    'Combinatorial explosion in its natural habitat.',
    'If you think you understand all paths, you\'re wrong.',
  ],
  utilityBlob: [
    'A namespace wearing an OOP costume.',
    'This is not a class, it\'s a collection of functions in witness protection.',
    'Procedural code masquerading as OOP.',
    'Static methods: because inheritance is too mainstream.',
    'Why make instances when you can just hoard static methods?',
    'This class is what happens when someone misses C.',
    'Oop (object-oriented programming) without the oop.',
    'A graveyard of abandoned static methods.',
    'Stateless, homeless, and proud of it.',
    'The UNIX philosophy but make it Java.',
    'If it\'s not a method, it must be a static method.',
    'Class in name only. Function collection in spirit.',
    'This is what your high school teacher warned you about.',
    'It\'s not OOP, it\'s just a very large namespace file.',
    'The kitchen sink learned to program.',
    'Refactoring: I\'m scared of breaking everything.',
    'Singleton? More like Staticton.',
    'Every method is static. Every class is lonely.',
    'The procedural programmer\'s exit strategy.',
  ],
  paramHoarder: [
    'Just use a data class, please.',
    'Method signatures so long they need their own build pipeline.',
    'Parameter list reads like a grocery store receipt.',
    'How many arguments is *too many* arguments? Ask this method.',
    'Bet you can\'t pronounce all these parameters without stopping for air.',
    'This method comes with a tutorial just to invoke it.',
    'The parameter that ate Tokyo.',
    'Listing parameters: a 10-minute TED talk.',
    'Method call requires an IDE autocomplete just to remember the order.',
    'This signature should come with a warning label.',
    'I\'ve seen function pointers with fewer parameters.',
    'The method that\'s its own dependency injection container.',
    'Calling this method requires a PhD in the method itself.',
    'The method signature that doesn\'t fit on a monitor.',
    'At what point do we call a constructor?',
    'Parameter overload: the gift that keeps on giving.',
    'The method that asked for everything and got it.',
    'Needs a parameter object the size of a small class.',
    'Method signature: available in regular and ultra-extended.',
    'Parameter bloat in its purest form.',
  ],
  paramPusher: [
    'Getting suspicious up here.',
    'Five parameters? You\'re on thin ice, buddy.',
    'Might want to introduce a parameter object before this gets worse.',
    'One more parameter and we call a meeting.',
    'Parameters breeding like rabbits.',
    'Creeping complexity, one parameter at a time.',
    'The slippery slope in action.',
    'Warning: Approaching God Parameter Syndrome.',
    'Not quite overboard. Not quite elegant.',
    'The beginning of a beautiful monster.',
    'You\'re one parameter away from a data class.',
    'Almost there. Keep going and you hit the wall.',
    'On the edge of needing an intervention.',
    'The parameter escalation clause.',
    'This method is one parameter away from needing a vision statement.',
  ],
  matryoshka: [
    'A class inside a class. It\'s classes all the way down.',
    'Nesting dolls have fewer layers than this.',
    'Inception (2010) called, it wants its structure back.',
    'How deep does the rabbit hole go?',
    'Why not just extract this to its own file, I wonder?',
    'Nested types? I prefer "structural procrastination."',
    'This is what happens when you\'re afraid to commit to a new file.',
    'Turtles all the way down.',
    'The matryoshka doll of antipatterns.',
    'Each layer hiding secrets from the last.',
    'This is your sign to press ctrl+X and create a new file.',
    'Lazily nested, boldly regretted.',
    'The class that was too shy to be public.',
    'Layers of indirection: a retrospective.',
    'Hiding in plain sight. Multiple times.',
    'This class is afraid of the public eye.',
    'Encapsulation taken to paranoid levels.',
    'Nesting levels: 1, 2, 3, infinity.',
    'This file is a Russian doll factory.',
  ],
  silentType: [
    'The author assumes you know. You do not.',
    'Zero comments on code that desperately needs narration.',
    'If you can read this, congratulations, you\'re psychic.',
    'Comments would help, but we\'re living dangerously today.',
    'Documentation? Never heard of her.',
    'This code is a mystery wrapped in an enigma wrapped in regret.',
    'Comments are for the weak. (Please add comments.)',
    'Future maintainers will write StackOverflow questions about this.',
    'The code that speaks for itself. Loudly and unintelligibly.',
    'Your code review: "Um... what does this do?"',
    'The Rosetta Stone hasn\'t been deciphered faster.',
    'Self-documenting code is a myth. This proves it.',
    'Written in pure intent and zero explanation.',
    'The author\'s brain was too busy to explain.',
    'If it compiles, it ships. Understanding is optional.',
    'The code that speaks only to itself.',
    'Your IDE\'s autocomplete knows more about this than you do.',
    'Leave a comment? But then people might use this correctly!',
    'The programmer\'s version of leaving no trace.',
    'Silent type, loud regrets.',
    'This code came with no user manual.',
  ],
  complexityChamp: [
    'This building earned every floor.',
    'Complexity score that makes other types blush.',
    'A monument to "just one more feature."',
    'This class is its own documentation warning.',
    'Complexity so high, the intern cried.',
    'Your code review feedback would need bullet points.',
    'The complexity champion. Undisputed heavyweight.',
    'Refactoring this would require a flowchart AND a whiteboard AND a therapist.',
    'Earned its complexity stripes the hard way.',
    'The poster child for "why does this need to be so complicated?"',
    'Beauty and complexity: the eternal trade-off. Chose complexity.',
    'Reaching legendary status in complication.',
    'This is what happens when feature creep meets no refactoring.',
    'The gift that keeps on giving. To your headaches.',
    'This is the kind of complexity that makes architects cry.',
    'Earned every bit of its McCabe number.',
    'The complexity poster child.',
    'A Gordian knot of your own making.',
    'Complicated on purpose? Or by accident? (Yes.)',
    'The class that complexity metrics fear.',
  ],
  tallestTower: [
    'Standing tall. For now.',
    'Impressively vertical. Alarmingly monolithic.',
    'The skyline\'s crown jewel. The refactor\'s nightmare.',
    'Tall, dark, and complex.',
    'Height achieved through accumulation of decisions.',
    'Breaking the tower of abstraction, one method at a time.',
    'Reaching toward the sky. Toward destiny. Toward a refactor.',
    'The skyscraper nobody planned for.',
    'Vertical and impressive. Structurally questionable.',
    'Building upward instead of outward. Classic mistake.',
    'The tower of power made of spaghetti code.',
    'Monolithic monuments: a retrospective.',
    'Tall enough to see the refactoring needed from space.',
    'Verticality as a sign of ambition (and poor design decisions).',
    'Vertical integration nobody asked for.',
    'Standing on the shoulders of... wait, where\'s the base?',
    'A monument to "we\'ll refactor this later."',
    'The higher they build, the harder they fall.',
    'Skyrise coding at its finest.',
    'This tower needs an elevator. And a lot of therapy.',
  ],
};

/**
 * Pick a random quip for a code smell type.
 */
export function getRandomQuip(smellType) {
  const quips = CODE_SMELL_QUIPS[smellType];
  if (!quips || quips.length === 0) {
    return null;
  }
  return quips[Math.floor(Math.random() * quips.length)];
}

